version: 0.0
os: linux
files:
  - source: / # Source location within the S3 bucket
    destination: /var/www/html # Destination on the EC2 instance

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/configure_permissions.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
